spring:
  application:
    name: postservice

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/careerhub_posts?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: ${SERVER_PORT:8082}
